version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_DATABASE=terra_energy
      - DB_USERNAME=root
      - DB_PASSWORD=root

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8001/api
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: terra_energy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  ml_service:
    build: ./ml_service
    ports:
      - "5000:5000"
    volumes:
      - ./ml_service:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
